-- Business Analysis 

select * from Books;
select * from Orders;
select * from Customers;

--Q1 What are the total sales/revenue generated by the bookstore?
select sum(total_amount) as total_revenue
from Orders;

--Q2 Who are the top 10 customers by total spending?
select customer_id,
sum(total_amount) as total_spending
from Orders
group by customer_id
order by total_spending desc
limit 10;

--Q3 Which are the top 10 best-selling books?
select book_id,
sum(qunatity) as total_sales
from Orders 
group by book_id
order by total_sales desc
limit 10;

--Q4 Which genre generates the highest revenue?
select b.genre,
sum(o.total_amount) as revenue
from Orders o
join Books b on b.book_id=o.book_id
group by b.genre
order by revenue desc
limit 1;

--Q5 Which author generates the highest revenue?
select b.author,
sum(o.total_amount) as revnue
from Orders o
join Books b on b.book_id=o.book_id
group by b.author
order by revnue desc
limit 1;

--Q6 Which country generates the highest revenue?
select c.country,
sum(o.total_amount) as revnue
from Orders o
join Customers c on c.customer_id=o.customer_id
group by c.country
order by revnue desc
limit 1;

--Q7 What is the average order value?
select avg(total_amount) as average_ordervalue
from Orders ;

--Q8 Which books should be restocked?
select title,stock,
case 
when stock<5 then 'restock'
else 'enough stock'
end as stock_status
from Books 
where stock<5;

--Q9 Which books have high stock but very low sales?
select b.book_id,b.title,b.stock,
coalesce (sum(o.qunatity),0) as total_sold
from Books b
left join Orders o on b.book_id=o.book_id
group by b.book_id,b.title,b.stock
having b.stock>20
and coalesce(sum(o.qunatity),0)<5;

--Q10 What is the monthly revenue trend?
select 
date_trunc('month', order_date) as month,
sum(total_amount) as revenue 
from Orders 
group by 1
order by 1;

--Q11 Which month generated the highest revenue?
select 
date_trunc('month', order_date) as month,
sum(total_amount) as revenue 
from Orders 
group by 1
Order by revenue desc
limit 1;

