
-- intermediate Sql

--Q1 Display customer names along with their all order details.
select c.name,o.*
from Orders o
inner join Customers c
on c.customer_id=o.customer_id;

--Q2 Display order ID, customer name, book title and quantity.
select o.order_id,o.qunatity,c.name,b.title
from Orders o
inner join Customers c
on o.customer_id=c.customer_id
inner join Books b
on o.book_id=b.book_id;

--Q3 Display all customers including customers who haven't placed an order.
select * from Customers c
left join Orders o on o.customer_id=c.customer_id
where order_id is null;

--Q4 Display all books including books that have never been ordered.
select * from Books b
left join Orders o on b.book_id=o.book_id 
where order_id is null;

--Q5 Count the total number of customers.
select count(Customer_id) from Customers

--Q6 Count the number of books in each genre.
select genre,count(title) 
from Books
group by (genre);

--Q7 Calculate total revenue generated by each book.
select b.title,sum(o.total_amount) as total_revenue
from Orders o
join Books b on o.book_id=b.book_id
group by(title);

--Q8 Calculate total spending by each customer.
select c.name,sum(o.total_amount) as total_spending
from Orders o
join Customers c on o.customer_id=c.customer_id
group by(name);

--Q9 Find customers who have placed more than 2 orders.
select c.name,c.customer_id,count(o.order_id) as total_orders
from customers c
join Orders o
on c.customer_id=o.customer_id
group by name,c.customer_id
having count(o.order_id)>2;

--Q10 Find genres having more than 10 books.
select genre ,count(*) as total_books
from Books
group by(genre)
having count(*)>10;

--Q11 Calculate average book price for each genre.
select genre, avg(price)
from Books
group by(genre);

--Q12 Find books whose price is higher than the average book price.
select title,book_id ,price
from Books
where price>(select avg(price) from Books);

--Q13 Find the highest-priced book in each genre.
select b.book_id,b.title,b.genre,b.price
from Books b
where b.price=(select max(b1.price) from Books b1
where b.genre=b1.genre);

--Q14 Find books that have never been ordered.
select * from Books b
left join Orders o
on o.book_id= b.book_id
where o.book_id is null





